amqp-host: localhost
amqp-port: 5672
amqp-username: artemis
amqp-password: artemis
"%dev":
   quarkus:
     flyway:
       camel:
         location: db/camel/migration
         migrate-at-start: true
quarkus:
  artemis:
    url: tcp://${amqp-host}:61616
    username: ${amqp-username}
    password: ${amqp-password}
  datasource:
    camel:
      db-kind: postgresql
      username: ${DB_USERNAME:application}
      password: ${DB_PASSWORD:application}
      jdbc:
        url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:application}
        max-size: 16
        transactions: xa
mp:
  messaging:
    outgoing:
      out:
        connector: smallrye-amqp
        container-id: producer
        durable: true
        use-anonymous-sender: false
