camel:
  context:
    name: ${quarkus.application.name}
  send-route:
    period: PT5S
quarkus:
  application:
    name: jms-sender
  artemis:
    url: tcp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    username: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  pooled-jms:
    pooling:
      enabled: true
    max-connections: 2
