version: "3.7"

services:
  # postgres + pgadmin4 web UI
  postgres:
    image: postgres:14.1-alpine@sha256:884c142deb4a141f67489c807534ec6139f13b9a6432d2f87a4de283aaec0b5c
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: application
    ports:
      - "5432:5432"
    command:
      - --max_prepared_transactions=100

  # apache activemq-artemis
  artemis:
    image: vromero/activemq-artemis:2.16.0-alpine@sha256:2621ab238411031e364cc219c621f20a6613efc3a91b43c85148e8872e6b3163
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/artemis/var/lib/artemis/etc-override:/var/lib/artemis/etc-override/:ro
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
  #service
  service:
    profiles:
      - service
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile.quarkus-ubi
    ports:
      - "8080:8080"
    env_file: service/.env
    deploy:
      resources:
        limits:
          memory: 80m
        reservations:
          memory: 100m
    depends_on:
      - artemis
      - postgres