camel:
  context:
    name: ${quarkus.application.name}
quarkus:
  application:
    name: jms-receiver
  qpid-jms:
    url: amqp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    username: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  datasource:
    db-kind: postgresql
    devservices:
      enabled: false
    data:
      db-kind: postgresql
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
      jdbc:
        url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:application}
        max-size: 4
        transactions: xa
  flyway:
    data:
      locations: db/camel/migration
      migrate-at-start: true
  http:
    port: 8081
