camel:
  context:
    name: ${quarkus.application.name}
quarkus:
  application:
    name: jms-receiver
  artemis:
    url: tcp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    username: ${ARTEMIS_USERNAME:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}
  datasource:
    db-kind: postgresql
    devservices:
      enabled: false
    data:
      db-kind: postgresql
      username: ${DB_USERNAME:application}
      password: ${DB_PASSWORD:application}
      jdbc:
        url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:application}
        max-size: 4
        transactions: xa
  flyway:
    data:
      locations: db/camel/migration
      migrate-at-start: true
  http:
    port: 8081
  pooled-jms:
    pooling:
      enabled: true
    max-connections: 2
    transaction: xa
  transaction-manager:
    enable-recovery: true

"%test":
  quarkus:
    artemis:
      url: tcp://test:123456
      username: foo
      password: bar